#!/bin/bash

# deploy Drupal

set -e          # Exit immediately if a command exits with a non-zero status.

# load some Openshift functions
source $OPENSHIFT_CARTRIDGE_SDK_BASH

DRUPAL_SITE_DIR=${OPENSHIFT_DATA_DIR}sites
DRUPAL_PRIVATE_DIR=${OPENSHIFT_DATA_DIR}private
DRUPAL_SETTINGS=${DRUPAL_SITE_DIR}/default/settings.php

echo "echo $DRUPAL_SITE_DIR $DRUPAL_PRIVATE_DIR $DRUPAL_SETTINGS"
client_result "client_result $DRUPAL_SITE_DIR $DRUPAL_PRIVATE_DIR $DRUPAL_SETTINGS"

# Set the initial password
admin_pwd=$(generate_password)

mkdir -p ${DRUPAL_SITE_DIR}/default
mkdir -p ${DRUPAL_PRIVATE_DIR}

pushd ${OPENSHIFT_REPO_DIR}php
echo "Creating a new Drupal site at ${DRUPAL_SITE_DIR}/default"
# drush site-install standard --site-name=${OPENSHIFT_APP_NAME} \
#     --account-pass=$admin_pwd \
#     --db-url=mysql://$OPENSHIFT_MYSQL_DB_USERNAME:$OPENSHIFT_MYSQL_DB_PASSWORD@$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/$OPENSHIFT_APP_NAME \
#     --yes

# NEED:
# lines 56 - 133
# line 60 drush install


